{{ if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: infrabox-metrics
  namespace: {{ template "system_namespace" . }}
  labels:
    app: infrabox
spec:
  selector:
    matchLabels:
      app: infrabox-metrics
  endpoints:
  - port: web
{{ end }}
