{{ if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: infrabox
  namespace: {{ template "system_namespace" . }}
spec:
  serviceAccountName: infrabox
  serviceMonitorSelector:
    matchLabels:
      app: infrabox
  resources:
    requests:
      memory: 400Mi
{{ end }}
