{{ if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ template "system_namespace" . }}
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: infrabox
{{ end }}
