{{ if eq .Values.cluster.name "master" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: infrabox-static
    namespace: {{ template "system_namespace" . }}
    labels:
        app: infrabox-static
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: infrabox-static
        spec:
            {{ include "imagePullSecret" . | indent 8 }}
            containers:
            -
                name: static
                image: {{ include "image_repository" . }}/static:{{ include "image_tag" . }}
                imagePullPolicy: Always
{{ end }}
